//
//  InfoViewController.swift
//  3FA
//
//  Created for E102 Final Project in the 2022 Fall Semester
//
//  Team members:
//  Ellie Baker
//  Skye Barnes
//  Shayla Battle
//  Griffin Tomaszewski

import UIKit

class InfoViewController: UIViewController {

    //info variables
    var selectedTopic: String!
    @IBOutlet var info: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view
        //formatting label containing info
        info.numberOfLines = 0
        info.lineBreakMode = .byWordWrapping
        info.adjustsFontSizeToFitWidth = true
        
        //setting text for each topic, could also be stored in a text file in the future
        if(selectedTopic == "Creating a Password") {
            info.font = UIFont(name: "Arial", size: 12.0)
            info.text = "\tWhen creating a new login for any account but especially for your work account, it is crucial that you have a secure password. Secure passwords are unique, hard to guess, and relatively easy to remember.    \n\n\tMaking a unique password: You shouldn’t reuse passwords for multiple accounts or websites. If you do, one leaked or guessed password means a hacker has access to multiple accounts.\n\n\tMaking a hard-to-guess password: Your password should have between 13 and 20 characters to be secure. The longer the password, the harder it is to guess using random combinations of characters. Even if a website requires less characters, your password should be at least 13 characters and utilize uppercase and lowercase letters, numbers, and special characters. Your password should not be a common word or phrase that replaces some letters with symbols, as those are commonly used and easy to guess. Using a variation of P@s$W0rd?! or aBc123! is a very bad idea and could lead to your account being hacked. Using variations of your name, username, or website name is also a bad idea.\n\n\tMaking an easy-to-remember password: Your secure password has to be something you’ll remember. Although it can be difficult to remember many secure passwords, you should avoid writing passwords down or storing them in a digital note or document. Instead, invest in a secure password manager. Good password managers will encrypt your login information in their database, analyze the strength of your passwords, and let you know when a website you have an account on has a security breach.  Although many good password managers require a paid subscription, the security benefits over other password-keeping methods is worth the cost. Don’t use built-in password managers in browsers like Chrome or Safari.\n\n\tChanging Your Password: To be truly secure, you should change your passwords regularly, especially for important accounts like your work login or banking account. If there is a chance that your login information may have been compromised, change it immediately. Otherwise, change your passwords every few months or on a quarterly basis. When you change your password, it should be a completely different password, not a variation of your old one."
        } else if(selectedTopic == "Two-Factor Authentication") {
            info.font = UIFont(name: "Arial", size: 20.0)
            info.text = "\tIs a secure password enough to create a secure account? No! Utilizing two-factor authentication adds another layer of security to your account. Common forms of two-factor authentication include security questions, one-time passwords, or an authentication app. Your work login requires you to set up a security question and verify your login through this app. When selecting a security question, you should not select one that many people would know the answer to. For example, if your first pet had a common name or you posted a lot about them online, you should not use that as your security question and answer, as it would be easy for someone to guess. Using an authentication app is more secure, as it requires you to personally verify your login. If you are not actively logging in to your account, never verify a login attempt."
        } else if(selectedTopic == "WiFi") {
            info.font = UIFont(name: "Arial", size: 20.0)
            info.text = "\tThe first step to staying secure online is using secure WiFi. Using WiFi that doesn’t require a password or WiFi in public places can be risky. You should never log in to important accounts over these networks. That includes your work account. If you are unsure about the security of a WiFi network, set up a secure mobile hotspot instead or wait to access your account on a secure network. Public and unsecured networks can allow people on the network to view the online activity of others using the network. This activity can include what websites you visit and what login credentials you use."
        } else if(selectedTopic == "Secure Websites") {
            info.font = UIFont(name: "Arial", size: 16.0)
            info.text = "\tThe next step to staying secure online is avoiding unsecured websites. How do you know if a website is safe? When you visit a website, if the URL starts with https://, it is secure. If the URL starts with http://, it is not secure. Most browsers will show a closed lock next to the URL if a website is secure, but you should always double check the URL before putting in personal, login, or payment information. You should also ensure that the rest of the URL is correct, as there are many websites that impersonate common websites as an attempt to steal your login information. If you are unsure about the security of a website, you should not use it.\n\n\tMany websites will ask your permission to use cookies, but what are cookies? Cookies are small files that store data about your usage of a website. This includes information about your device, ad preferences, setting preferences, and auto-fill information. There are different types of cookies: some are okay and some are bad. As a precaution, you should not accept cookies on most websites, and you should clear your cookies frequently. This can be done in your browser settings."
        } else if(selectedTopic == "Downloading from the Internet") {
            info.font = UIFont(name: "Arial", size: 20.0)
            info.text = "\tYou should always be careful on the internet but especially when downloading something. Internet downloads can be secretly filled with malware, ransomware, spyware, or other viruses and malicious code. How do you know if a download from the internet is safe? You should only download something from the internet if you absolutely must and you should make sure that you are downloading what you intend. Before downloading, check that the website you are downloading from is secure. It should also be from a known website. Downloading things from piracy websites or online message boards and forums is a bad idea, as those downloads are not monitored and could contain malicious code. If you are confident that it is safe to download something, you should run a virus scan on your computer after you have installed it. If you discover that you have a virus on your computer, you should report it immediately."
        } else if(selectedTopic == "Scams") {
            info.font = UIFont(name: "Arial", size: 20.0)
            info.text = "\tMany people are probably able to identify scam calls pretty well, but a good rule of thumb is to be wary if a) it’s a call from someone you don’t know, b) it’s an offer that seems too good to be true, c) the caller requires your login information or payment information, d) the caller claims that you have an urgent problem you weren’t previously aware of. If you receive a call that seems suspicious, hang up. If you fall victim to a scam call, it can affect the security of all your accounts, including your work account."
        } else if(selectedTopic == "Phishing") {
            info.font = UIFont(name: "Arial", size: 11.0)
            info.text = "\tWhat is a phishing attack? Phishing attacks occur when you receive a fraudulent email and respond with personal, login, or payment information, or click on a link or attachment containing malicious code. Being able to spot phishing attacks is critical for maintaining security. A phishing email can be spotted by the email address, written message, or path of the links.\n\n\tSpotting a fraudulent email address: When you receive an email containing links, attachments, or a request for information, the first thing you should do is check the email address. If it is from an individual, do you know them? Is this their actual email address? If you are unsure, it is wise to contact them another way to verify they actually sent you the email. If the email is from a company or organization, were you expecting the email? Is that the email address the one that company or organization usually uses? If you are unsure, you can search the company’s actual email address or call their help center to verify the address.\n\n\tSpotting a phishing message: Red flags in an email message include urgency, uncharacteristic writing, or unusual requests. If you receive an email with a sense of urgency or one meant to instill panic, remain calm and do not act immediately. Check the email address and think logically about the message. For example, if you receive an urgent request for money via a bank transfer, call the person before responding. Think about whether they may actually need money and if you would be the one they would ask. Would they email you or call you? If you receive a purchase confirmation that you did not make, call the company or your bank to see if a fraudulent purchase was actually made. If you receive an email that contains a lot of spelling and grammar mistakes or sounds uncharacteristic of the person you think it’s coming from, it’s likely fraudulent. Other detailed mistakes can give away an imposter. Lastly, emails with usual requests should be approached with extreme caution. Emails requesting personal, login, or payment information are likely fraudulent. Most companies will never contact you directly asking for information. Never share sensitive information over email. Gmail also has a built in function where you can report phishing attempts if an email seems off.\n\n\tSpotting a suspicious link: Although it is tempting to click on a link to figure out what it is, DON’T. Hover your mouse over a link to see the URL it leads to without clicking on it. If that URL is not what you were expecting from the link or if it is to an unsecure website, do not click it. Clicking on suspicious links can infect your computer and network with malware or allow a hacker access. "
        } else if(selectedTopic == "Using this App") {
            info.font = UIFont(name: "Arial", size: 20.0)
            info.text = "\tCongratulations! Making it to this page means you already made an account and logged in. This app verifies your identity through your employee ID and first and last name. If any of this information does not match up, your account can not be created.\n\n\tWhen it comes to authentication, when you get a request you can choose an employee to verify your authentication and then verify it yourself. This is more secure than other 2FA apps because this is actually three factor authentication, requiring another employee to verify you before you can access any secured information. \n\n\tThere is also a section in the app to review past logins. If you see any unusual logins, you should immediately change your account information as it has likely been compromised. There is also the educational section, which you are reviewing right now. When you are done reviewing this info, there is a quiz over all of the topics at the bottom of the educational modules page."
        } else {
            info.font = UIFont(name: "Arial", size: 20.0)
            info.text = "\tThe best way to prevent cyber attacks is to recognize cybersecurity weaknesses and attack attempts before they occur. Now that you’ve learned about those things, what do you do if a cyber attack does occur? First, disconnect the device you are on and any device you believe may be affected from the internet. Disconnect any ethernet cables or other data cables from the device (all cables except for charging). Once you have done this, report the attack using the feature on this app. If you do not hear from an IT specialist within fifteen minutes, you should call the IT department directly. Before you hear from IT, do not log in on any device or reconnect the affected devices. After IT responds, you should follow their instructions exactly. Although dealing with a cyber attack may be an inconvenience in the short term, it will save money and potentially lives in the long run. Don’t hesitate to report an attack, no matter how embarrassing the circumstances."
        }
    }

}
